name: weather_counter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  routemaster: ^1.0.1
  key_value_storage:
    path: packages/key_value_storage
  weather_api:
    path: packages/weather_api
  user_repository:
    path: packages/user_repository
  main_screen:
    path: packages/features/main_screen
  domain_models:
    path: packages/domain_models
  component_library:
    path: packages/component_library


dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true