ffarb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: main_screen_localizations.dart
output-class: MainScreenLocalizations
synthetic-package: false
nullable-getter: false

